### ISSUE TITLE
What's your development setup look like?

### ISSUE THREAD

**Issue by benpolinsky** [dyjakan/ruby-rails-interview-questions#1]
I find this asked more often than not.

**Comment by dyjakan** [comment]
Now that you mention it, yes I also got this question almost in every interview.

I think it fits more into Rails section, mostly because one can elaborate on linters and other tools that help debug on-the-fly.

@benpolinsky What do you think?

**Comment by dyjakan** [comment]
Added to Rails section. ✌️
