### ISSUE TITLE
#Ruby

### ISSUE THREAD

**Issue by kattak2k** [dyjakan/ruby-rails-interview-questions#2]
Few questions I have faced in interview.

1. What is duck typing?
2. Explain rails engine.
3. explain polymorphic association.
4. explain has_many :through association.

and I have many questions on git, are you interested in adding a new section??

**Comment by dyjakan** [comment]
1 and 2 are 👌

As for 3 and 4, I am not sure. We already have _"Explain ActiveRecord's associations (all of them)"_, granted it's less specific but points the reader into associations themselves and I think it should be enough (i.e. one just need to re-read chapter about associations from Rails Guides).

**Comment by dyjakan** [comment]
Oh-my, forgot to respond to second part of your question.

I don't think that mixing-in questions about git (or any other VCS) is right thing to do as they belong more to operations part of the development process. However, I can certainly mention VCS software in meta section. What do you think? @kattak2k

**Comment by dyjakan** [comment]
Closing. 1 and 2 were added. 3 and 4 were rejected.
